ConnectionString javadoc
odnoklassniki/one-nio pull request #84
Opened 2024-06-17 22:52 UTC by surovenko

Also I have changed param **clientMaxPoolSize** from **10** to **5000** because **http client** from **one-nio** usually used for high-load system where we need a lot of connections and value 5000 more suitable for such cases. And because of poor docs it's not obvious how to increase this value. I bet a lot of developers like me starting to use http client on production and realised that the performance is terrible, although all integration tests were normal, since 10 sockets per address are enough for tests.

2024-06-25 16:23 UTC, incubos requested changes
Thank you for your contribution, but there are some suggestions.

2024-06-25 16:23 UTC, incubos commented on src/one/nio/pool/SocketPool.java
> +              conn.getIntParam("clientMaxPoolSize", 5000),
Altering defaults is extremely hazardous in such projects. Please, revert this change.

2024-06-25 16:23 UTC, incubos commented on src/one/nio/net/ConnectionString.java
> + * proxy
What do you think about adding monospaced formatting?

2024-06-25 19:09 UTC, surovenko commented
@incubos not sure what "monospaced formatting" is. Could you please provide some example with this? Can't find any in google. Thanks!

2024-06-29 12:43 UTC, incubos commented
> @incubos not sure what "monospaced formatting" is. Could you please provide some example with this? Can't find any in google. Thanks!

Here is [some example](https://github.com/odnoklassniki/one-nio/blob/d24eefa3e7166275e795842f73c0834caebe4886/src/one/nio/mem/Malloc.java#L23), otherwise the formatting will be unaligned.

2024-06-30 14:19 UTC, surovenko commented
@incubos done

2024-07-01 09:27 UTC, incubos requested changes
New unit test doesn't pass:
```
[ERROR] Failures: 
[ERROR]   ConnectionStringTest.testConnectionStrings:57 expected:<[def]> but was:<[?]>
```

2024-07-15 09:21 UTC, surovenko commented
@incubos fixed

2024-08-29 12:37 UTC, incubos approved these changes
Thank you for your contribution!

2024-08-29 12:37 UTC, merged