Input/OutputStream support
odnoklassniki/one-nio pull request #86
Opened 2024-11-07 08:12 UTC by MacX19

Added `DeserializeInputStream` and `PersistOutputStream`. Contain `readObject()` and `writeObject()` methods and work similarly to the standard `ObjectInputStream` and `ObjectOutputStream`.

2025-01-22 07:41 UTC, lehvolk commented
@MacX19 could you please merge the upstream to your PR

2025-01-23 07:35 UTC, MacX19 commented
> @MacX19 could you please merge the upstream to your PR

done

2025-01-27 18:57 UTC, lehvolk requested changes

2025-01-28 08:19 UTC, MacX19 commented on src/one/nio/serial/DeserializeInputStream.java
> +            super(new byte[400]);
I don't know, I just copy the default size from PersistStream
https://github.com/odnoklassniki/one-nio/blob/dd6d16309c09b3fd298cd2dc170e37e648ca106c/src/one/nio/serial/PersistStream.java#L24-L26
You can change the initial size, it doesn't make much difference, the array size will be increased if necessary.
Or you can remove this constructor and use the following one

2025-01-28 09:06 UTC, lehvolk commented on src/one/nio/serial/DeserializeInputStream.java
> +            super(new byte[400]);
Let's have a constant for this placed in PersistStream for example

2025-01-28 10:41 UTC, MacX19 commented on src/one/nio/serial/DeserializeInputStream.java
> +            super(new byte[400]);
I've commited the changes. Is that what you mean?

2025-01-28 11:56 UTC, lehvolk approved these changes

2025-01-28 11:57 UTC, merged

2025-01-28 11:57 UTC, lehvolk commented
@MacX19 thanks for contribution!